services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: daphne -e tcp:8000:interface=0.0.0.0 xris.asgi:application
    working_dir: /app/xris
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ${MEDIA_ROOT}:/app/media
    env_file:
      - .env
    environment:
      DATABASE_HOST: host.docker.internal
      DATABASE_PORT: 5432
    depends_on:
      - redis
      - rabbitmq

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A xris worker --loglevel=info
    working_dir: /app/xris
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DATABASE_HOST: host.docker.internal
      DATABASE_PORT: 5432
    depends_on:
      - redis
      - rabbitmq

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      celery -A xris beat
      --loglevel=info
      --scheduler django
      --schedule=/app/celerydata/celerybeat-schedule
    working_dir: /app/xris
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DATABASE_HOST: host.docker.internal
      DATABASE_PORT: 5432
    depends_on:
      - redis
      - rabbitmq

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A xris flower --port=5555 --address=0.0.0.0
    working_dir: /app/xris
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DATABASE_HOST: host.docker.internal
      DATABASE_PORT: 5432
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"