# Generated by Django 5.2 on 2025-04-24 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_receipt_url',
        ),
    ]
