# Generated by Django 5.2 on 2025-05-26 13:42

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutXMPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='What is X-Band Multiparameter Radar?', max_length=200)),
                ('paragraph_1', models.TextField()),
                ('paragraph_2', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.gallery_image_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Empowering Rainfall Intelligence', max_length=200)),
                ('subtitle', models.TextField(default='XRIS is a web-based platform to access, analyze, and visualize data...')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='XRIS', max_length=100)),
                ('short_description', models.CharField(default='X-Band Radar Information System', max_length=255)),
                ('logo', models.ImageField(help_text='Logo image', upload_to='xris/project/logo/')),
                ('favicon', models.ImageField(help_text='Favicon image', upload_to='xris/project/favicon/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.avatar_upload_path),
        ),
    ]
