# Generated by Django 5.2 on 2025-05-27 13:03

import processor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmprdata',
            name='csv',
            field=models.FileField(upload_to=processor.models.upload_to_csv),
        ),
        migrations.AlterField(
            model_name='xmprdata',
            name='geotiff',
            field=models.FileField(upload_to=processor.models.upload_to_tiff),
        ),
        migrations.AlterField(
            model_name='xmprdata',
            name='image',
            field=models.FileField(upload_to=processor.models.upload_to_png),
        ),
    ]
