# Generated by Django 5.2 on 2025-05-28 06:44

import django.db.models.deletion
import processor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_alter_xmprdata_csv_alter_xmprdata_geotiff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RainMapImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('image', models.ImageField(upload_to=processor.models.upload_to_jpeg)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RainMapDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rainmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='processor.rainmapimage')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
